apiVersion: v1
kind: Service
metadata:
  name: simple-api-server-tls
  labels:
    app.kubernetes.io/name: simple-api-server-tls
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simple-api-server-tls
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
